jwt:
    issuer: z82714567@gmail.com
    secret: 8vkYGHWdnnAY9OzGSmT3TVhY2GPHL36o
logging:
    file:
        name: log/Sboard.log
    level:
        jdbc:
            connection: info
            resultsettable: info
            sqlonly: info
            sqltiming: info
        org:
            hibernate: info
            springframework:
                security: debug
        root: info
server:
    servlet:
        context-path: /
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: zp426486!!ZP
        url: jdbc:mysql://13.124.4.134:3306/Jboard
        username: root
    devtools:
        livereload:
            enabled: true
        restart:
            enabled: true
    jpa:
        database: mysql
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_sql: true
                use_sql_comments: true
    security:
        user:
            name: user
            password: 1234
    thymeleaf:
        cache: false
        #prefix 설정을 안하면 HTML 수정 후 브라우저에서 새고로침 반영 안돼
        #그리고 반드시 classpath 경로로 쓰고 templates 마지막 / (controller return 주소가 뒤에 붙음)붙이면 배포파일 실행 안돼
        prefix: classpath:/templates
        #prefix: file:src/main/resources/templates/

    servlet:
        multipart:
            location: src/main/resources/static/file/
            max-file-size: 10MB

